### PR TITLE
Client/Server registration

### LINKED ISSUE #179: Send the registration credentials to the server
- email
- nickname
- password

#168

### LINKED ISSUE #180: Verify the emailed entered matches expected email syntax
example@email.com

#168

### LINKED ISSUE #181: Validate registration credentials.
Make sure the email and nickname are both unique.

#168

### LINKED ISSUE #182: Setup Hashing of Passwords
I'm not sure if we made a final verdict on hashing on the client side vs hashing on the server side.

### LINKED ISSUE #184: Send registration result to client.
#168

### PR DESCRIPTION
**Pull request by camja014**
- [x] Update DB schema to allow NameFirst to be NULL.
- [x] Client: Validate textbox input.
- [x] Client: Construct registration object and send to the server.
- [x] Server: Handle registration request.
- [x] Client: Handle server's response to the registration request.
- [x] Setup password hashing
closes #179, closes #184, closes #181, closes #180, closes #182

### CODE REVIEW

**Comment by camja014** [comment]
I converted JungleClient to a singleton as we only need one instance of the client, and this will make it easier for the controller classes to access the client instance for sending messages to the server.

**Comment by camja014** [comment]
I added some notes to issue #179

**Comment by camja014** [comment]
Alrighty, all code should be in place... Here goes nothing....

EDIT: And there is blood everywhere....

**Comment by camja014** [comment]
The request is making it server side now. It just looks like nothing happens...

**Comment by camja014** [comment]
Registration is mostly working now!

**Comment by camja014** [comment]
Ready for merging.

**Review by amgunden — APPROVED** [review]

**Pull request merged**
